Pack protobuf-java JAR as an external library to the publishing ZIP
To resolve the following class not found issue.

```
[2022-01-11 21:56:49,028] SEVERE {b7a.log.crash} - com/google/protobuf/DescriptorProtos$FileDescriptorSet
java.lang.NoClassDefFoundError: com/google/protobuf/DescriptorProtos$FileDescriptorSet
	at io.ballerina.stdlib.grpc.protobuf.cmd.DescriptorsGenerator.generateRootDescriptor(DescriptorsGenerator.java:138)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.generateBalFile(GrpcCmd.java:236)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:156)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.DescriptorProtos$FileDescriptorSet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```